// src/Web/dijitalatolye-web-ng/src/app/layouts/app-layout/app-layout.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatButtonModule } from '@angular/material/button';
import { AuthStore } from '@core/auth/auth.store';

@Component({
  selector: 'da-app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, MatIconModule, MatMenuModule, MatButtonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`:host { display: block; min-height: 100%; }`],
  template: `
    <div class="min-h-full flex flex-col bg-slate-50">
      <header class="bg-white border-b border-brand-100/70 sticky top-0 z-30">
        <div class="max-w-7xl mx-auto px-4 h-14 flex items-center justify-between gap-4">
          <a routerLink="/" class="flex items-center gap-2 font-bold text-brand-700 shrink-0">
            <span class="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 text-white">
              <mat-icon class="!text-white" style="font-size:16px;width:16px;height:16px">auto_awesome</mat-icon>
            </span>
            <span class="hidden sm:inline">DijitalAtölye</span>
          </a>

          <nav class="flex items-center gap-1 overflow-x-auto">
            @if (isTeacher()) {
              <a routerLink="/teacher/dashboard" routerLinkActive="bg-brand-100 !text-brand-700"
                 class="px-3 py-1.5 rounded-lg text-sm font-medium text-slate-600 hover:text-brand-700 hover:bg-brand-50 transition">Panel</a>
              <a routerLink="/teacher/contents" routerLinkActive="bg-brand-100 !text-brand-700"
                 class="px-3 py-1.5 rounded-lg text-sm font-medium text-slate-600 hover:text-brand-700 hover:bg-brand-50 transition">İçeriklerim</a>
              <a routerLink="/teacher/contents/new" routerLinkActive="bg-brand-100 !text-brand-700"
                 class="px-3 py-1.5 rounded-lg text-sm font-medium text-slate-600 hover:text-brand-700 hover:bg-brand-50 transition">Yükle</a>
            }
            @if (isEditor()) {
              <a routerLink="/editor" routerLinkActive="bg-brand-100 !text-brand-700" [routerLinkActiveOptions]="{ exact: true }"
                 class="px-3 py-1.5 rounded-lg text-sm font-medium text-slate-600 hover:text-brand-700 hover:bg-brand-50 transition">Editör</a>
              <a routerLink="/editor/queue" routerLinkActive="bg-brand-100 !text-brand-700"
                 class="px-3 py-1.5 rounded-lg text-sm font-medium text-slate-600 hover:text-brand-700 hover:bg-brand-50 transition">Kuyruk</a>
            }
            @if (isAdmin()) {
              <a routerLink="/admin" routerLinkActive="bg-brand-100 !text-brand-700" [routerLinkActiveOptions]="{ exact: true }"
                 class="px-3 py-1.5 rounded-lg text-sm font-medium text-slate-600 hover:text-brand-700 hover:bg-brand-50 transition">Yönetim</a>
            }
          </nav>

          <div class="flex items-center gap-2 shrink-0">
            <a routerLink="/notifications" routerLinkActive="bg-brand-100 !text-brand-700"
               class="inline-flex items-center justify-center w-9 h-9 rounded-lg text-slate-600 hover:bg-brand-50 hover:text-brand-700 transition"
               aria-label="Bildirimler">
              <mat-icon style="font-size:18px;width:18px;height:18px">notifications</mat-icon>
            </a>

            <button mat-button [matMenuTriggerFor]="userMenu" class="inline-flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-brand-50 text-slate-700">
              <div class="w-7 h-7 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 text-white text-xs font-bold flex items-center justify-center">
                {{ initial() }}
              </div>
              <span class="hidden md:inline text-sm">{{ email() }}</span>
              <mat-icon style="font-size:14px;width:14px;height:14px">expand_more</mat-icon>
            </button>
            <mat-menu #userMenu="matMenu">
              <div class="px-4 py-3 border-b border-slate-100" style="min-width:220px">
                <p class="text-xs text-slate-500">Giriş yapan</p>
                <p class="text-sm font-medium text-slate-900 truncate">{{ email() }}</p>
                <p class="text-xs text-slate-500 mt-0.5">{{ rolesLabel() }}</p>
              </div>
              @if (isTeacher()) {
                <a mat-menu-item routerLink="/teacher/profile">Profilim</a>
              }
              @if (isAdmin()) {
                <a mat-menu-item routerLink="/admin/reports">Raporlar</a>
              }
              <button mat-menu-item (click)="logout()" class="!text-rose-700">
                <mat-icon class="!text-rose-700">logout</mat-icon>
                <span>Çıkış</span>
              </button>
            </mat-menu>
          </div>
        </div>
      </header>
      <main class="flex-1 max-w-7xl w-full mx-auto px-4 py-6"><router-outlet /></main>
    </div>
  `,
})
export class AppLayoutComponent {
  private readonly auth = inject(AuthStore);
  private readonly router = inject(Router);

  readonly email = this.auth.email;
  readonly isAdmin = this.auth.isAdmin;
  readonly isEditor = this.auth.isEditor;
  readonly isTeacher = this.auth.isTeacher;
  readonly initial = computed(() => (this.auth.email() ?? '?').charAt(0).toUpperCase());
  readonly rolesLabel = computed(() => this.auth.roles().join(', ') || '—');

  logout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

// src/Web/dijitalatolye-web/src/layouts/AppLayout.tsx
import { Link, NavLink, Outlet, useNavigate } from "react-router-dom";
import { Sparkles, Bell, LogOut, ChevronDown } from "lucide-react";
import { useState } from "react";
import { useAuthStore } from "@/state/auth";

export default function AppLayout() {
  const navigate = useNavigate();
  const { email, roles, logout } = useAuthStore();
  const [menuOpen, setMenuOpen] = useState(false);
  const isAdmin = roles.includes("Admin") || roles.includes("SuperAdmin");
  const isEditor = isAdmin || roles.includes("Editor");
  const isTeacher = isEditor || roles.includes("Teacher");

  const linkCls = ({ isActive }: { isActive: boolean }) =>
    `px-3 py-1.5 rounded-lg text-sm font-medium transition ${
      isActive ? "bg-brand-100 text-brand-700" : "text-slate-600 hover:text-brand-700 hover:bg-brand-50"
    }`;

  return (
    <div className="min-h-full flex flex-col bg-slate-50">
      <header className="bg-white border-b border-brand-100/70 sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-4 h-14 flex items-center justify-between gap-4">
          <Link to="/" className="flex items-center gap-2 font-bold text-brand-700 shrink-0">
            <span className="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 text-white">
              <Sparkles className="w-4 h-4" />
            </span>
            <span className="hidden sm:inline">DijitalAtölye</span>
          </Link>

          <nav className="flex items-center gap-1 overflow-x-auto">
            {isTeacher && (
              <>
                <NavLink to="/teacher/dashboard" className={linkCls}>Panel</NavLink>
                <NavLink to="/teacher/contents" className={linkCls}>İçeriklerim</NavLink>
                <NavLink to="/teacher/contents/wizard" className={linkCls}>Yükle</NavLink>
              </>
            )}
            {isEditor && (
              <>
                <NavLink to="/editor" className={linkCls} end>Editör</NavLink>
                <NavLink to="/editor/queue" className={linkCls}>Kuyruk</NavLink>
              </>
            )}
            {isAdmin && <NavLink to="/admin" className={linkCls} end>Yönetim</NavLink>}
          </nav>

          <div className="flex items-center gap-2 shrink-0">
            <NavLink to="/notifications"
              className={({ isActive }) =>
                `inline-flex items-center justify-center w-9 h-9 rounded-lg transition ${
                  isActive ? "bg-brand-100 text-brand-700" : "text-slate-600 hover:bg-brand-50 hover:text-brand-700"
                }`
              }
              aria-label="Bildirimler">
              <Bell className="w-4 h-4" />
            </NavLink>

            <div className="relative">
              <button onClick={() => setMenuOpen((v) => !v)}
                className="inline-flex items-center gap-2 px-2 py-1.5 rounded-lg hover:bg-brand-50 text-slate-700">
                <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-brand-500 to-brand-700 text-white text-xs font-bold flex items-center justify-center">
                  {(email ?? "?").charAt(0).toUpperCase()}
                </div>
                <span className="hidden md:inline text-sm">{email}</span>
                <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
              </button>
              {menuOpen && (
                <>
                  <div className="fixed inset-0 z-10" onClick={() => setMenuOpen(false)} />
                  <div className="absolute right-0 mt-2 w-56 rounded-xl bg-white border border-slate-200 shadow-lg z-20 overflow-hidden">
                    <div className="px-4 py-3 border-b border-slate-100">
                      <p className="text-xs text-slate-500">Giriş yapan</p>
                      <p className="text-sm font-medium text-slate-900 truncate">{email}</p>
                      <p className="text-xs text-slate-500 mt-0.5">{roles.join(", ") || "—"}</p>
                    </div>
                    {isTeacher && (
                      <Link to="/teacher/profile" onClick={() => setMenuOpen(false)}
                        className="block px-4 py-2 text-sm text-slate-700 hover:bg-brand-50">
                        Profilim
                      </Link>
                    )}
                    {isAdmin && (
                      <Link to="/admin/reports" onClick={() => setMenuOpen(false)}
                        className="block px-4 py-2 text-sm text-slate-700 hover:bg-brand-50">
                        Raporlar
                      </Link>
                    )}
                    <button
                      onClick={() => { setMenuOpen(false); logout(); navigate("/login"); }}
                      className="w-full text-left px-4 py-2 text-sm text-rose-700 hover:bg-rose-50 inline-flex items-center gap-2">
                      <LogOut className="w-4 h-4" /> Çıkış
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </header>
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 py-6"><Outlet /></main>
    </div>
  );
}
