// src/Web/dijitalatolye-web-ng/src/app/shared/cookie-banner/cookie-banner.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';

const STORAGE_KEY = 'dijitalatolye-cookie-consent';

@Component({
  selector: 'da-cookie-banner',
  standalone: true,
  imports: [RouterLink, MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (visible()) {
      <div class="fixed bottom-4 inset-x-4 md:inset-x-auto md:right-6 md:max-w-md z-50">
        <div class="rounded-2xl bg-white border border-brand-200 shadow-xl shadow-brand-900/10 p-5">
          <div class="flex items-start gap-3">
            <div class="w-10 h-10 rounded-lg bg-brand-50 text-brand-700 flex items-center justify-center shrink-0">
              <mat-icon style="font-size:20px;width:20px;height:20px">cookie</mat-icon>
            </div>
            <div class="flex-1">
              <h3 class="font-semibold text-slate-900 text-sm">Çerez kullanımı</h3>
              <p class="mt-1 text-xs text-slate-600 leading-relaxed">
                Hizmetimizi iyileştirmek için yalnızca gerekli teknik çerezleri kullanıyoruz.
                Detay için <a routerLink="/kvkk" class="text-brand-700 hover:text-brand-800 underline">KVKK</a> sayfamıza bakın.
              </p>
              <div class="mt-3 flex gap-2">
                <button (click)="accept()"
                  class="px-3 py-1.5 rounded-lg bg-brand-600 text-white text-xs font-semibold hover:bg-brand-700">Kabul ediyorum</button>
                <button (click)="dismiss()"
                  class="px-3 py-1.5 rounded-lg border border-slate-300 text-slate-700 text-xs font-medium hover:bg-slate-50">Daha sonra</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    }
  `,
})
export class CookieBannerComponent {
  readonly visible = signal(this.isBannerNeeded());

  private isBannerNeeded(): boolean {
    try { return localStorage.getItem(STORAGE_KEY) !== 'accepted'; }
    catch { return false; }
  }

  accept(): void {
    try { localStorage.setItem(STORAGE_KEY, 'accepted'); } catch { /* noop */ }
    this.visible.set(false);
  }

  dismiss(): void { this.visible.set(false); }
}

// src/Web/dijitalatolye-web/src/components/CookieBanner.tsx
import { useEffect, useState } from 'react';

const STORAGE_KEY = 'dijitalatolye-cookie-consent';

export default function CookieBanner() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (!localStorage.getItem(STORAGE_KEY)) setVisible(true);
  }, []);

  function accept() {
    localStorage.setItem(STORAGE_KEY, 'accepted');
    setVisible(false);
  }

  if (!visible) return null;

  return (
    <div className="fixed bottom-0 inset-x-0 z-50 p-4">
      <div className="max-w-4xl mx-auto bg-white border shadow-lg rounded-xl p-4 flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
        <p className="text-sm text-slate-700">
          Deneyiminizi iyileştirmek için çerezler kullanıyoruz.{' '}
          <a href="/kvkk" className="text-brand-600 underline">KVKK</a>
        </p>
        <button type="button" onClick={accept} className="btn-primary shrink-0">
          Kabul et
        </button>
      </div>
    </div>
  );
}
